### ISSUE TITLE
Feature Request: Allow chaining of matrix multiplication without temporaries

### ISSUE THREAD

**Issue by jeremysalwen** [viennacl/viennacl-dev#126]
If we have an operation such as

    C=(A+B)x

This could be represented by

    C=linalg::prod(A+B,x)

but this fails to compile.

Likewise, it also fails to chain with element-wise products

    C=linalg::prod(linalg::element_prod(A,B),x);

It would be cool if operations such as these coul be implemented without temporaries using template magic.

**Comment by karlrupp** [comment]
Although it seems strange at first sight, not using template magic at this point is actually intentional: We found that matrix-matrix multiplications don't perform well if additional arguments trash the cache. Thus, overall performance is higher if there is an explicit temporary. (Not to mention other difficulties such as OpenCL just-in-time compilation)

Since element_prod() and other functions create such temporaries if needed, it is inconsistent that prod() does not create a temporary, but instead compilation fails. Hence, I consider this to be the task associated with this issue.

**Comment by PhilippeTillet** [comment]
Jeremy, could you clarify. After reading your other post, I got confused.
Are you referring to matrix-vector multiplication or matrix-matrix
multiplication ? (C = (A + B)x is a bit unclear :p)
If you are referring to matrix-vector multiplication, temporaries can and
should be removed. You may be able to achieve that using the code-generator
directly (although it's pretty tedious). Removing the temporaries
automatically is not planed for ViennaCL 1.7.0, as it involves quite some
messy tree parsing to preserve correctness when temporaries shouldn't be
removed.

**Comment by jeremysalwen** [comment]
I am referring to marix-vector multiplication.

I currently just using temporaries.  Are there examples of using the code-generator in this fashion so I can judge how "messy" it would be?

**Comment by PhilippeTillet** [comment]
It is messy in the sense that it is pretty much unsupported (in the sense
that the generator will not throw error if it doesn't handle the
operation). Because it's not supported, there's no example.

something like this should work (or close enough) for a simple matrix
vector product (non transposed), I think:

namespace ds = viennacl::device_specific;

viennacl::ocl::context const & ctx = A.context();
ds::row_wise_reduction_template
generator(ds::builtin_database::row_wise_reduction_params(ctx.current_device(),
'N'), 'N')
viennacl::scheduler::statement operation(y, op_assign(), prod(A + B, x));
ds::execute(generator, operation,  operation, ctx)

**Comment by cdeterman** [comment]
I know this issue was closed but I'm not sure my question warrants opening a new one.  The above works but there doesn't appear to be overloads for the `trans` function which would naturally follow with these chained `prod` operations.  A simple example:

    trans(vcl_A - vcl_B);

This currently doesn't compile.

**Comment by karlrupp** [comment]
Back in the early days when trans() was introduced, the ViennaCL API ran into compilation errors if the computation would have required a temporary object. Over time, this has shifted towards 'silent' temporary objects, since in most cases compiler errors are more troublesome than a temporary object here and there.

Long story short: I think it's better to also allow such chained operations for trans(). However, I can't promise a fix for 1.7.0, yet I'll see what I can do. :-)

**Comment by karlrupp** [comment]
@cdeterman  As the extensions for trans() haven't made it into the 1.7.0 release, I've created a separate issue: #149
