### ISSUE TITLE
Trying to write a kernel using viennacl

### ISSUE THREAD

**Issue by ahazra** [viennacl/viennacl-dev#132]
I am newbie in GPU computing and trying to use ViennaCL for my purpose.
Roughly the pattern of the Code is 

typedef  double ScalarType;
typedef viennacl::matrix<ScalarType,viennacl::column_major> VCLMatrixType;
typedef Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor> eigenMat;

eigenMat eigen_x0 = eigenMat::Random(3,n);
VCLMatrixType vcl_x0 (3,n);
viennacl::copy(eigen_x0,vcl_x0);

for(time_counter =0; time_counter< time_end_counter; time_counter++)
{
   I have to write kernel here which will take some parameters param1(time_counter),
param2(time_counter), param3(time_counter) etc and create a separate 3 x 3 matrix  for each of the 
n column vectors
Also, n column vectors corresponding to each column.
Then 

  // here A (i) is the 3 x 3 matrix corresponding to i-th column 
// y(i) is a column vector corresponding  to i-th column
vcl_x0.col(i) = A(i) * vcl_x0.col(i) + y(i);
}

Would anyone please tell me how to write this kernel ? Thank you in advance.

**Comment by karlrupp** [comment]
How big is N here? For N smaller than ~5000 you most likely won't get good performance due to PCI-Express latency issues. 

Do you intend to use CUDA or OpenCL?

As for the kernel structure I'd recommend to allocate a viennacl::vector<ScalarType> with 3*3*N entries to represent A, and a viennacl::vector<ScalarType> with 3*N entries to represent x0. The i-th block of A is then stored at indices 9*i to 9*i+8 and the i-th vector of length 3 in x0 at indices 3*i to 3*i+2. In your kernel (confer to https://github.com/viennacl/viennacl-dev/blob/master/examples/tutorial/custom-cuda.cu for a custom CUDA kernel and https://github.com/viennacl/viennacl-dev/blob/master/examples/tutorial/custom-kernels.cpp for a custom OpenCL kernel) you then assign one GPU thread to each of the matrix products. This should give you quite good performance for a start, but only require a few lines of kernel code. Further optimizations can be applied later once this first kernel works.

Please understand that we do not have the resources available for writing full application-specific kernels for our users.

**Comment by ahazra** [comment]
Thank you for your suggestion. I exactly wanted that .I wanted to write a kernel where I will assign one GPU thread to each of the matrix products.

**Comment by ahazra** [comment]
I was playing with the tutorial problem custom-cuda.cu. I found something very strange.

    



        #include <iostream>
       #include <string>

         #ifndef VIENNACL_WITH_CUDA
              #define VIENNACL_WITH_CUDA
        #endif


// ViennaCL headers
           #include "viennacl/vector.hpp"
          #include "viennacl/matrix.hpp"
          #include "viennacl/linalg/matrix_operations.hpp"
          #include "viennacl/linalg/norm_2.hpp"
         #include "viennacl/linalg/prod.hpp"


// Some helper functions for this tutorial:
#include "Random.hpp"

template<typename NumericT>
__global__ void elementwise_multiplication(const NumericT * vec1,
                                           const NumericT * vec2,
                                                 NumericT * result,
                                           unsigned int size)
{
  for (unsigned int i = blockDim.x * blockIdx.x + threadIdx.x;
                    i < size;
                    i += gridDim.x * blockDim.x)
    result[i] = vec1[i] * vec2[i];
}

/**
* With this let us go right to main():
**/
int main()
{
    typedef double       NumericType;
   std::size_t N = 5;

  NumericType * device_vec1;
  NumericType * device_vec2;
  NumericType * device_result;
 
  cudaMalloc(&device_vec1,   N * sizeof(NumericType));
  cudaMalloc(&device_vec2,   N * sizeof(NumericType));
  cudaMalloc(&device_result, N * sizeof(NumericType));

 std::vector<NumericType> temp(N);
  for (std::size_t i=0; i<temp.size(); ++i)
    temp[i] = NumericType(i);
  cudaMemcpy(device_vec1, &(temp[0]), temp.size() * sizeof(NumericType), cudaMemcpyHostToDevice);

  for (std::size_t i=0; i<temp.size(); ++i)
    temp[i] = NumericType(2*i);
  cudaMemcpy(device_vec2, &(temp[0]), temp.size() * sizeof(NumericType),  cudaMemcpyHostToDevice);

viennacl::vector<NumericType> vcl_vec1(device_vec1, viennacl::CUDA_MEMORY, N);
  viennacl::vector<NumericType> vcl_vec2(device_vec2, viennacl::CUDA_MEMORY, N);
  viennacl::vector<NumericType> vcl_result(device_result, viennacl::CUDA_MEMORY, N);

std::cout << "Using existing kernel within ViennaCL:" << std::endl;
  elementwise_multiplication<<<128, 128>>>(vcl_vec1.handle().cuda_handle().get(),
                                           vcl_vec2.handle().cuda_handle().get(),
                                           vcl_result.handle().cuda_handle().get(),
                                           N);

  std::cout << "vec1  : " << vcl_vec1 << std::endl;
  std::cout << "vec2  : " << vcl_vec2 << std::endl;
  std::cout << "result: " << vcl_result << std::endl;

std::cout << "!!!! TUTORIAL COMPLETED SUCCESSFULLY !!!!" << std::endl;

  return EXIT_SUCCESS;
}
