### ISSUE TITLE
Your preference on ViennaCL extensions?

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#134]
My question is generically, if I copy the ViennaCL header files and place them in another program, how would you like credit applied to you?  I ask as I am not particularly familiar with the MIT licensing.

Some specific context.  I am primarily an R developer.  I'm not sure how familiar you are with the language but it is quite common to have R packages that have a backend using C++ libraries.  To make it simpler for R developers/users some C++ libraries are re-purposed in to their own respective packages.  Probably the most widely known package doing this is the [BH package](https://github.com/eddelbuettel/bh) where the boost headers are put in the package to make the interfacing more concise for other R packages.  I would like to do the same with ViennaCL as I am very interested in extending the GPU capabilities of R.  You can see the preliminary package on my github page, [RViennaCL](https://github.com/cdeterman/RViennaCL).  Before I do much more development I wanted to ask you about this and get your thoughts.

As I have already said, ViennaCL is a wonderful library and I look forward to both using it and watching it develop over time (hopefully with a cleaner interface for R programmers).

**Comment by karlrupp** [comment]
The license file merely states "(...) The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. (...)". As long as this is the case, everything is okay (MIT was chosen simply because it is so permissive) :-)

I'm very happy to see a ViennaCL-based package in development for R, particularly as I occasionally use R for some high-quality plots. RViennaCL certainly passes the credit on because of its name, and you also provide a link to the ViennaCL webpage. The only other thing that comes to my mind is to ask for any feedback on what we can do to make ViennaCL better - but this apparently has nothing to do with credit :-)

**Comment by cdeterman** [comment]
Fair enough, just wanted to make you aware before I start trying to get it accepted by CRAN.  I will probably wait for the formal release of 1.7.0 though.  Did you have a timeline in mind?

**Comment by karlrupp** [comment]
1.7.0 is hopefully out by June 12. If it misses that date, it's likely going to be end of June.

**Comment by karlrupp** [comment]
ViennaCL 1.7.0 is out. Is there anything left to be done in this issue?

**Comment by cdeterman** [comment]
No, we should be able to close this issue.
