### ISSUE TITLE
Segmentation fault at program termination on Intel's windows implementation.

### ISSUE THREAD

**Issue by ptillet** [viennacl/viennacl-dev#154]
This pretty annoying bug was consistently observed accross a bunch of projects (arrayfire, clFFT ...). I could partly reproduce it with ViennaCL.
The segmentation fault occurs at program termination when some variables with static scope are destroyed. Specifically, it occurs when static variables call clRelease\* upon destruction. It is implementation-specific and will only happen with some SDKs. I could observe it on Linux when using Intel's proprietary OpenCL implementation with Beignet's ICD.

It was mentioned in the source code of clFFT (https://github.com/clMathLibraries/clFFT/blob/master/src/library/repo.h : _NOTE: We can't release resources in our destructor because as a static object, the order of destruction of static objects is not guaranteed, and openCL might already have cleaned itself up. When clFFT tries to free its resources, an access violation could occur._), and a similar issue was spotted and "solved"  in arrayfire (https://github.com/arrayfire/arrayfire/issues/549, https://github.com/arrayfire/arrayfire/commit/7c11266b1bc112268b71282867ce5c21a5018e68).

I think the root of the issue is the call to dlopen or LoadLibrary that will not register the OpenCL implementation as a dependency, and cause shared objects to potentially get unloaded in an undefined order (http://blogs.msdn.com/b/oldnewthing/archive/2005/05/23/421024.aspx). On my personal projects, I adopted the same technique as arrayfire/clFFT by not releasing the OpenCL handles upon termination (ie, using static pointers that can only be deleted through an API call..).

**Comment by karlrupp** [comment]
I've seen such stuff happening already back in 2010 on Mac OS, but wasn't aware of the problems with Intel's SDK on Windows. As far as I can tell the only clean fix for this is to replace current singletons based on 'static' with reference-counting and automatic clean-up when the last ViennaCL object is destroyed. This, however, brings along a bunch of other problems, because there are situations where no ViennaCL objects exist, but a context destruction is inappropriate. Super-simple example:

    for (...) do_something_with_viennacl();

The cleanest solution is to introduce something like ViennaCLInitialize() and ViennaCLFinalize() to have a well-defined scope. This comes natural with a shared library interface, so I scheduled this for ViennaCL 2.0.0.
