### ISSUE TITLE
Accessing cl::Platform information

### ISSUE THREAD

**Issue by cdeterman** [viennacl/viennacl-dev#204]
In straight OpenCL with the C++ header you would often get platform information with the following:

```c++
//cl::Platform plat;
plat.getInfo<CL_PLATFORM_NAME>()
```

I couldn't find any methods with the `viennacl::ocl::platform` classes to access this information beyond the `info()` method which provides limited information that would need to be parsed.  Similar methods as `viennacl::ocl::device` would be ideal.

A secondary question, is there a way to get the actual `cl::Platform` object out of the ViennaCL objects?  Then these things could be done directly as well.

**Comment by karlrupp** [comment]
You can get the `platform_index()` from a viennacl::ocl::context and then access the respective context via an object of type `viennacl::ocl::platform`, which takes the platform index as a constructor argument. For full platform information you can get the `cl_platform_id` via the member `.id()` and use the OpenCL functions as usual.

Since every ViennaCL object also stores a context, this way you can get access to the platform.

**Comment by cdeterman** [comment]
That did the trick, thank you.
