### ISSUE TITLE
Kernel generator?

### ISSUE THREAD

**Issue by tsmithe** [viennacl/viennacl-dev#223]
Hi hi,

I'm trying to get back into ViennaCL. I noticed that in some historic papers, the generator interface is suggested as a nice method for caching fused kernels (eg [http://epubs.siam.org/doi/pdf/10.1137/120903683]). The generator had a nice API, but seems to have been totally replaced with the advent of the scheduler (or perhaps I have missed something?). Is the recommended way now to use the scheduler expression tree interface directly? It seems that this interface does not expose all ViennaCL's basic operations (though I do not have a list of missing ones to hand, so I could be wrong).

**Comment by karlrupp** [comment]
The generator interface was ultimately discarded because it was built on top of expression templates and *really* hard to interface with everything else. In particular, one could not set up expressions at runtime. The current scheduler should be seen as a runtime-enabled version of the generator.

At the same time, the scheduler isn't perfect, but at the very least should expose all basic matrix and vector operations. If it does not, please file specific issues and they will get fixed :-)

**Comment by tsmithe** [comment]
Yes, I thought so. The nice thing about the generator was its elegant 'symbolic' interface, but I remember discussing it before; using the scheduler interface is much more verbose!

I will let you know if I discover anything missing; I was thinking before of using it in relation to the expression in issue #224, and the 'missing' feature was the row_sum operation (but of course it could be encoded using the prod-ones method). My reason for being interested in the #224 expression is simply that I am interested in efficiently computing the norms of the rows of a matrix, as the sample code suggests.
